"""Generic single-database configuration with an async dbapi."""
from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0aa8780778'
down_revision: Union[str, None] = '80e834a9e825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rack_name', sa.String(length=50), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rack_name', 'row', 'column', name='uq_rack_row_col')
    )
    op.create_table('medicine_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'location_id', name='uq_medicine_location')
    )
    with op.batch_alter_table('medicine_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_locations_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_locations_medicine_id'), ['medicine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_locations_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_locations_location_id'))

    op.drop_table('medicine_locations')
    op.drop_table('storage_locations')
    # ### end Alembic commands ###
