"""Generic single-database configuration with an async dbapi."""
from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645f9964bc43'
down_revision: Union[str, None] = '372e09656ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sold_by', sa.String(length=255), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_transactions_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_transactions_sold_at'), ['sold_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_transactions_sold_at'))
        batch_op.drop_index(batch_op.f('ix_sales_transactions_medicine_id'))

    op.drop_table('sales_transactions')
    # ### end Alembic commands ###
