"""Generic single-database configuration with an async dbapi."""
from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c139d1a6da'
down_revision: Union[str, None] = '4e0aa8780778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_call_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caller', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('medicines', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('assignments', sa.Text(), nullable=True),
    sa.Column('supplier_followups', sa.Text(), nullable=True),
    sa.Column('reminder_created', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('structured_extraction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_call_records_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_call_records_timestamp'))

    op.drop_table('voice_call_records')
    # ### end Alembic commands ###
