"""Generic single-database configuration with an async dbapi."""
from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372e09656ab4'
down_revision: Union[str, None] = '004_widen_extraction_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_finance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('electricity_and_bills', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('staff_salaries', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_finance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_finance_month'), ['month'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_finance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_finance_month'))

    op.drop_table('monthly_finance')
    # ### end Alembic commands ###
