"""Generic single-database configuration with an async dbapi."""
from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd74b9ba0fc'
down_revision: Union[str, None] = 'ca2a61b9db21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('qr_code_image', sa.String(), nullable=True))
        batch_op.create_index('ix_medicines_qr_code_id', ['qr_code_id'], unique=True)
        batch_op.create_unique_constraint(None, ['qr_code_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_medicines_qr_code_id')
        batch_op.drop_column('qr_code_image')
        batch_op.drop_column('qr_code_id')

    # ### end Alembic commands ###
