"""Generic single-database configuration with an async dbapi."""
from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51099f28fb96'
down_revision: Union[str, None] = 'c82f99d9cb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('related_medicine_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_related_medicine_id'), ['related_medicine_id'], unique=False)

    op.create_table('staff_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_medicine_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_tasks_related_medicine_id'), ['related_medicine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_tasks_related_medicine_id'))

    op.drop_table('staff_tasks')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_related_medicine_id'))

    op.drop_table('reminders')
    op.drop_table('decision_audit_log')
    # ### end Alembic commands ###
