"""Generic single-database configuration with an async dbapi."""
from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80e834a9e825'
down_revision: Union[str, None] = '14ac8ba78642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('medicine_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reminder_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('reminder_time', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('repeat_interval', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('stop_condition', sa.String(length=255), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_reminders_related_medicine_id'))
        batch_op.create_index(batch_op.f('ix_reminders_medicine_id'), ['medicine_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('reminders_related_medicine_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('recurrence_pattern')
        batch_op.drop_column('completed')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('related_medicine_id')
        batch_op.drop_column('reminder_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('related_medicine_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recurrence_pattern', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reminders_related_medicine_id_fkey'), 'medicines', ['related_medicine_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_reminders_medicine_id'))
        batch_op.create_index(batch_op.f('ix_reminders_related_medicine_id'), ['related_medicine_id'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('stop_condition')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('last_reminded_at')
        batch_op.drop_column('active')
        batch_op.drop_column('repeat_interval')
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('reminder_type')
        batch_op.drop_column('medicine_id')
        batch_op.drop_column('pharmacy_id')

    # ### end Alembic commands ###
